# app/workflows/intelligent_agent.py
from typing import TypedDict, Annotated, Literal
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field
import os

# Import existing components
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from querying.hybrid_search import HybridResumeSearch
from generation.answer_generation import generate_answer
import sqlite3


# ============= State Definition =============
class AgentState(TypedDict):
    """State that flows through the agent graph"""

    query: str  # User's original question
    query_analysis: dict  # LLM's analysis of the query
    search_strategy: str  # Chosen strategy: "sql", "vector", "hybrid"
    sql_filters: dict  # Extracted SQL filters
    vector_query: str  # Reformulated query for vector search
    candidate_ids: list  # Resume IDs from SQL filtering
    search_results: list  # Raw search results
    final_results: list  # Deduplicated and enriched results
    answer: str  # Generated natural language answer
    should_retry: bool  # Whether to retry with different strategy
    retry_count: int  # Number of retries attempted
    use_llm_sql: bool  # Flag to use LLM-generated SQL on retry
    llm_generated_sql: str  # SQL query generated by LLM
    aggregation_result: float  # Result from aggregation queries (COUNT, AVG, etc.)
    chat_history: list[dict[str, any]]
    conversation_context: dict  # Candidates from previous conversation (for Q&A queries)


# ============= Query Analysis Models =============
class EntitiesModel(BaseModel):
    """Structured entities extracted from the query"""
    names: list[str] = Field(default_factory=list, description="Candidate names mentioned")
    skills: list[str] = Field(default_factory=list, description="Technical skills mentioned")
    companies: list[str] = Field(default_factory=list, description="Company names mentioned")
    locations: list[str] = Field(default_factory=list, description="Locations mentioned")
    degrees: list[str] = Field(default_factory=list, description="Educational degrees mentioned")
    job_titles: list[str] = Field(default_factory=list, description="Job titles mentioned")
    phone: str | None = Field(default=None, description="Phone number mentioned in query")
    email: str | None = Field(default=None, description="Email address mentioned in query")

class FiltersModel(BaseModel):
    """Structured filters extracted from the query"""
    candidate_ids: list[str] = Field(default_factory=list, description="Specific candidate IDs for follow-up queries")
    min_experience: float | None = Field(default=None, description="Minimum years of experience")
    max_experience: float | None = Field(default=None, description="Maximum years of experience")
    required_skills: list[str] = Field(default_factory=list, description="Required skills")
    location: str | None = Field(default=None, description="Location filter")
    company: str | None = Field(default=None, description="Company filter")
    job_title: str | None = Field(default=None, description="Job title filter")
    current_role: str | None = Field(default=None, description="Current role filter")
    phone: str | None = Field(default=None, description="Filter by phone number")
    email: str | None = Field(default=None, description="Filter by email address")
    institute: str | None = Field(default=None, description="Filter by educational institute/university")
    degree: str | None = Field(default=None, description="Filter by degree type (B.Tech, MBA, etc.)")
    project_keyword: str | None = Field(default=None, description="Filter by project name or technology")

class QueryAnalysis(BaseModel):
    """Structured output from query analyzer"""

    query_type: Literal[
        "name_based",
        "skill_based",
        "experience_based",
        "project_based",
        "education_based",
        "location_based",
        "contact_based",
        "complex_multi_criteria",
    ] = Field(description="Primary type of the query")

    intent: str = Field(
        description="What the user wants to know (e.g., 'find candidates', 'get education details', 'compare candidates')"
    )

    entities: EntitiesModel = Field(
        default_factory=EntitiesModel,
        description="Extracted entities: names, skills, companies, locations, degrees, etc."
    )

    filters: FiltersModel = Field(
        default_factory=FiltersModel,
        description="Structured filters: min_experience, max_experience, etc."
    )

    search_strategy: Literal["sql_first", "vector_first", "hybrid", "sql_only"] = Field(
        description="Recommended search strategy based on query analysis"
    )

    confidence: float = Field(
        description="Confidence in the analysis (0.0 to 1.0)", ge=0.0, le=1.0
    )

    reasoning: str = Field(
        description="Brief explanation of why this strategy was chosen"
    )
    is_refinement: bool = Field(
    description="True if this query refines/filters previous results, False if it's a new search",
    default=False
    )
    
    use_llm_sql: bool = Field(
        description="True if query requires LLM-generated SQL (complex logic, aggregations, counts, comparisons), False if hardcoded filters suffice",
        default=False
    )
    
    sql_complexity_reason: str = Field(
        description="Brief explanation of why LLM SQL is or isn't needed for this query",
        default=""
    )
    
    is_aggregation_query: bool = Field(
        description="True if query asks for COUNT, AVG, SUM, MAX, MIN or other aggregations (should return number/stats, not candidates)",
        default=False
    )
    
    is_qa_query: bool = Field(
        description="True if query asks to analyze/explain/suggest based on previous context WITHOUT needing new search (e.g., 'suggest questions based on his resume', 'explain his projects', 'why is he suitable')",
        default=False
    )


# ============= Complete Database Schema for LLM SQL Generation =============
DATABASE_SCHEMA = """
═══════════════════════════════════════════════════════════════════════════
COMPLETE DATABASE SCHEMA - Resume Intelligence System
═══════════════════════════════════════════════════════════════════════════

TABLE: parsed_resumes
─────────────────────────────────────────────────────────────────────────────
Primary table containing all parsed resume information.

COLUMNS:
├── resume_id (TEXT, PRIMARY KEY)
│   └── Unique identifier for each resume
│
├── document_id (TEXT, FOREIGN KEY → documents.document_id)
│   └── Links to the original uploaded document
│
├── BASIC INFORMATION:
│   ├── candidate_name (TEXT)
│   │   └── Full name of the candidate
│   │   └── Examples: "RATISH NAIR", "Shubham Baghel", "LAVANYA JAIN"
│   │
│   ├── email (TEXT)
│   │   └── Email address
│   │   └── Examples: "ratish.nair@example.com", "john.doe@gmail.com"
│   │
│   ├── phone (TEXT)
│   │   └── Phone number (may include country code, formatting varies)
│   │   └── Examples: "+91-8374106843", "9876543210", "(555) 123-4567"
│   │
│   └── location (TEXT)
│       └── Current location/city
│       └── Examples: "Bangalore", "New Delhi", "Mumbai, Maharashtra"
│
├── PROFESSIONAL SUMMARY:
│   ├── total_experience_years (REAL)
│   │   └── Total years of work experience (numeric, can be decimal)
│   │   └── Examples: 5.0, 3.5, 10.2, 0.0 (freshers)
│   │
│   └── current_role (TEXT)
│       └── Current job title/role
│       └── Examples: "Senior Software Engineer", "Data Scientist", "ML Engineer"
│
├── SKILLS (JSON stored as TEXT):
│   └── skills (TEXT)
│       └── JSON array of all technical and non-technical skills
│       └── Format: ["Python", "Java", "Machine Learning", "AWS", "React"]
│       └── Search using: skills LIKE '%Python%'
│
├── WORK EXPERIENCE (JSON stored as TEXT):
│   └── work_experience (TEXT)
│       └── JSON array of job objects
│       └── Format: [
│             {
│               "company": "Google",
│               "role": "Software Engineer",
│               "duration": "Jan 2020 - Present",
│               "responsibilities": ["Built ML pipelines", "Led team of 5"]
│             },
│             ...
│           ]
│       └── Search companies: work_experience LIKE '%Google%'
│       └── Search roles: work_experience LIKE '%Engineer%'
│
├── EDUCATION (JSON stored as TEXT):
│   └── education (TEXT)
│       └── JSON array of degree objects
│       └── Format: [
│             {
│               "degree": "B.Tech",
│               "field": "Computer Science",
│               "institute": "IIT Delhi",
│               "year": "2016-2020",
│               "grade": "8.5 CGPA"
│             },
│             ...
│           ]
│       └── Search institutes: education LIKE '%IIT%' OR education LIKE '%National Institute of Technology%'
│       └── Search degrees: education LIKE '%MBA%' OR education LIKE '%B.Tech%'
│
├── PROJECTS (JSON stored as TEXT):
│   └── projects (TEXT)
│       └── JSON array of project objects
│       └── Format: [
│             {
│               "name": "RAG System for Healthcare",
│               "description": "Built retrieval system...",
│               "technologies": ["Python", "LangChain", "ChromaDB"],
│               "role": "Lead Developer"
│             },
│             ...
│           ]
│       └── Search: projects LIKE '%RAG%' OR projects LIKE '%Healthcare%'
│
├── ACHIEVEMENTS & CERTIFICATIONS (JSON stored as TEXT):
│   └── additional_information (TEXT)
│       └── JSON containing achievements, certifications, awards, publications
│       └── Format: {
│             "achievements": ["Won hackathon 2023", "Published paper in ACM"],
│             "certifications": ["AWS Certified", "Google Cloud Professional"],
│             "languages": ["English", "Hindi"],
│             "hobbies": ["Photography", "Chess"]
│           }
│       └── Search: additional_information LIKE '%AWS Certified%'
│
└── METADATA:
    ├── parsed_at (TIMESTAMP)
    │   └── When the resume was parsed
    │
    └── indexed_at (TIMESTAMP)
        └── When the resume was indexed to vector store

═══════════════════════════════════════════════════════════════════════════

TABLE: documents
─────────────────────────────────────────────────────────────────────────────
Stores original uploaded PDF documents and extracted text.

COLUMNS:
├── document_id (TEXT, PRIMARY KEY)
├── batch_id (TEXT, FOREIGN KEY → upload_batches.batch_id)
├── raw_text (TEXT) - Full extracted text from PDF
├── original_filename (TEXT) - Original PDF filename
├── file_path (TEXT) - Path to stored PDF
├── status (TEXT) - Processing status: 'uploaded', 'extracted', 'parsed'
└── created_at (TIMESTAMP) - Upload timestamp

═══════════════════════════════════════════════════════════════════════════

IMPORTANT SEARCH PATTERNS:
─────────────────────────────────────────────────────────────────────────────

1. PHONE NUMBER SEARCH (handles different formats):
   WHERE REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(phone, '-', ''), ' ', ''), '(', ''), ')', ''), '+', '') LIKE '%8374106843%'

2. EDUCATION INSTITUTE SEARCH (flexible matching):
   WHERE education LIKE '%IIT%' OR education LIKE '%Indian Institute of Technology%'

3. SKILLS SEARCH (JSON array search):
   WHERE skills LIKE '%Python%' AND skills LIKE '%AWS%'

4. EXPERIENCE RANGE:
   WHERE total_experience_years BETWEEN 3 AND 5

5. COMPANY SEARCH:
   WHERE work_experience LIKE '%Google%' OR work_experience LIKE '%Microsoft%'

6. MULTI-CRITERIA:
   WHERE skills LIKE '%Python%' 
     AND total_experience_years >= 5 
     AND education LIKE '%IIT%'

7. AGGREGATIONS:
   SELECT COUNT(*) FROM parsed_resumes WHERE skills LIKE '%Python%'
   SELECT AVG(total_experience_years) FROM parsed_resumes WHERE education LIKE '%IIT%'
   SELECT candidate_name, total_experience_years FROM parsed_resumes ORDER BY total_experience_years DESC LIMIT 5

═══════════════════════════════════════════════════════════════════════════
"""


# ============= Initialize LLM =============
from dotenv import load_dotenv

load_dotenv()
# API key loaded from .env file

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.1,  # Low temperature for structured analysis
    max_tokens=4096
)

answer_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.1, max_tokens=4096)


# ============= Agent Nodes =============


def summarize_old_messages(messages: list, llm) -> str:
    """
    Summarize old chat messages to preserve context while reducing token usage

    Args:
        messages: List of old message dicts to summarize
        llm: The LLM instance to use for summarization

    Returns:
        A concise summary string
    """
    # Format messages for summarization
    conversation_text = ""
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        conversation_text += f"{role.upper()}: {content}\n\n"

    summarization_prompt = f"""You are an expert conversation summarizer for a resume search system. Your task is to create ultra-concise summaries that preserve ALL critical information.

CRITICAL RULES:
1. Extract and preserve ALL candidate names mentioned (with resume IDs if available)
2. Preserve ALL search criteria: skills, experience years, locations, companies, education
3. Preserve search refinements: "increased experience from 3 to 5 years", "added Python skill"
4. Use abbreviations: "exp" for experience, "yrs" for years, "ML" for Machine Learning
5. Use compact formats: "Python, Java, AWS" not "Python and Java and AWS"
6. Maximum 80 words - be extremely compact
7. Focus on FACTS, not conversational fluff

FEW-SHOT EXAMPLES:

Example 1:
USER: Find Python developers with more than 5 years experience
AGENT: Found 1 candidate: RATISH NAIR (resume_id: ccded4e6-ed27-4924-95b1-c2e312edc612) with 20 years experience, Python skills
USER: Show me their projects
AGENT: Displayed 15 projects for RATISH NAIR including Generative AI, RAG systems, MLOps
USER: What about their education?
AGENT: RATISH NAIR has B.Tech in Electronics & Communication from CUSAT (2000-2004)

SUMMARY:
Searched Python devs >5yrs exp. Found RATISH NAIR (ID: ccded4e6-ed27-4924-95b1-c2e312edc612, 20yrs exp). Discussed: 15 projects (Gen AI, RAG, MLOps), education (B.Tech Electronics CUSAT 2000-2004).

Example 2:
USER: Find candidates with Machine Learning experience in Bangalore
AGENT: Found 3 candidates in Bangalore with ML skills
USER: Show only those with 3+ years
AGENT: Narrowed to 2 candidates: Shubham Baghel, Anshika Chaudhary
USER: What companies did Shubham work at?
AGENT: Shubham worked at: Google, Microsoft, TCS

SUMMARY:
ML candidates in Bangalore, refined to 3+yrs: Shubham Baghel (ex-Google, Microsoft, TCS), Anshika Chaudhary.

Example 3:
USER: Find Java developers
AGENT: Found 8 Java developers
USER: Filter to those with AWS experience
AGENT: 5 candidates have both Java and AWS
USER: Show their current roles
AGENT: Current roles: 2 Senior Engineers, 2 Tech Leads, 1 Architect

SUMMARY:
Java devs (8 total) → refined to Java+AWS (5 candidates) → roles: 2 Sr Engineers, 2 Tech Leads, 1 Architect.

Example 4:
USER: Who has worked at Google?
AGENT: Found 4 candidates: Alex Kumar (resume_123), Priya Shah (resume_456), Raj Patel (resume_789), Sarah Lee (resume_012)
USER: Which ones know React?
AGENT: 2 candidates: Alex Kumar, Priya Shah have React skills
USER: Show Alex's education
AGENT: Alex Kumar: MS Computer Science Stanford 2018, BS MIT 2016

SUMMARY:
Ex-Google employees (4): Alex Kumar (ID: resume_123), Priya Shah (ID: resume_456), Raj Patel (ID: resume_789), Sarah Lee (ID: resume_012). Refined to React users: Alex, Priya. Alex edu: MS CS Stanford 2018, BS MIT 2016.

Now summarize this conversation using the same ultra-concise format:

CONVERSATION:
{conversation_text}

SUMMARY (max 80 words):"""

    try:
        response = llm.invoke(summarization_prompt)
        summary = response.content.strip()
        return summary
    except Exception as e:
        print(f"⚠️  Summarization failed: {e}")
        # Fallback: just list the topics
        return f"Previous conversation covered {len(messages)} messages about candidate search."




        
def analyze_query_node(state: AgentState) -> AgentState:
    """
    Node 1: Analyze user query to understand intent and plan strategy

    This is the BRAIN of the agent - decides what to do based on the question
    """

    # ============= BUILD CHAT CONTEXT =============
    chat_context = ""
    previous_candidate_ids = []
    most_recent_candidates = []  # ✅ Track MOST RECENT with names AND IDs

    if state["chat_history"]:
        history = state["chat_history"]

        # Extract candidates from chat history (process NEWEST first)
        for msg in reversed(history):
            if msg.get("role") == "agent":
                msg_ids = msg.get("candidate_ids", [])
                msg_names = msg.get("candidate_names", [])
                
                # Track MOST RECENT candidates (from last agent response)
                if not most_recent_candidates and msg_ids:
                    # Pair names with IDs
                    for i, cid in enumerate(msg_ids):
                        name = msg_names[i] if i < len(msg_names) else "Unknown"
                        most_recent_candidates.append({"id": cid, "name": name})
                
                # Collect all candidate IDs
                previous_candidate_ids.extend(msg_ids)

        # Remove duplicates from all IDs
        previous_candidate_ids = list(dict.fromkeys(previous_candidate_ids))

        # Check if we need to summarize (more than 10 messages)
        if len(history) > 10:
            # Split into old (to summarize) and recent (keep full)
            old_messages = history[:-10]  # All except last 10
            recent_history = history[-10:]  # Last 10 messages
            
            print(f"   📚 Summarizing {len(old_messages)} old messages...")
            summary = summarize_old_messages(old_messages, llm)
            
            chat_context = f"CONVERSATION SUMMARY (older messages):\n{summary}\n\n"
            chat_context += "RECENT CONVERSATION (last 10 messages):\n"
            
            # Format recent messages
            for i, msg in enumerate(recent_history, 1):
                role = msg.get("role", "unknown")
                content = msg.get("content", "")
                chat_context += f"{i}. {role.upper()}: {content}\n"
        else:
            # Short conversation, use all messages
            recent_history = history
            chat_context = "CONVERSATION HISTORY:\n"
            
            # Format all messages
            for i, msg in enumerate(recent_history, 1):
                role = msg.get("role", "unknown")
                content = msg.get("content", "")
                chat_context += f"{i}. {role.upper()}: {content}\n"

        # ✅ CRITICAL: Show MOST RECENT candidates with names for "these/those" pronoun resolution
        if most_recent_candidates:
            chat_context += f"\n📌 MOST RECENT CANDIDATES (use these for 'these'/'those'/'them' pronouns):\n"
            for i, cand in enumerate(most_recent_candidates[:10], 1):
                chat_context += f"   {i}. {cand['name']} (ID: {cand['id']})\n"
        
        # Show all discussed candidates if different from most recent
        if len(previous_candidate_ids) > len(most_recent_candidates):
            other_ids = [cid for cid in previous_candidate_ids if cid not in [c['id'] for c in most_recent_candidates]]
            if other_ids:
                chat_context += f"\n📋 OTHER CANDIDATES (earlier in conversation): {', '.join(other_ids[:5])}\n"
    
    # ✅ ALWAYS save conversation context to state for later use
    if most_recent_candidates:
        state["conversation_context"] = {
            "candidate_ids": [c["id"] for c in most_recent_candidates],
            "candidate_names": [c["name"] for c in most_recent_candidates]
        }
    
    # ============= QUERY ANALYSIS PROMPT =============
    analysis_prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """You are a query analyzer for a recruitment system. Your ONLY job is to extract structured information from user queries.

────────────────────────────────
YOUR TASK
────────────────────────────────
1. Extract entities (names, skills, locations, etc.) from the query
2. Classify the query type (skill_based, education_based, etc.)
3. Choose the search strategy (sql_only, sql_first, vector_first, hybrid)
4. Decide if LLM-generated SQL is needed (use_llm_sql flag)

────────────────────────────────
PRONOUN RESOLUTION
────────────────────────────────
When user uses pronouns (his/her/their/these/those/them):
- Look at 📌 MOST RECENT CANDIDATES section in chat context
- Extract the referenced candidate name(s) to entities.names
- Examples:
  • "Show their education" → extract names from MOST RECENT CANDIDATES
  • "His skills" → extract the single candidate from MOST RECENT CANDIDATES
  • "These 3 candidates" → extract first 3 from MOST RECENT CANDIDATES
"""),
            (
                "user",
                """{chat_context}

CURRENT QUERY: {query}

════════════════════════════════
STEP 1: EXTRACT ENTITIES
════════════════════════════════
Extract ALL explicitly mentioned information:

**Names:** Extract any candidate names mentioned
- Examples: "Lavanya Jain", "John Smith"
- Add to entities.names

**Contact Info:** Extract phone/email
- Phone: "8374106843", "+91-9876543210"
- Email: "john@example.com"
- Add to entities.phone and entities.email

**Companies:** Extract company names
- Add to entities.companies

════════════════════════════════
STEP 2: EXTRACT FILTERS
════════════════════════════════
Extract ALL criteria mentioned in the query:

**Skills:** "X developer" or "with X skill"
- "Python developers" → filters.required_skills = ["Python"]
- Extract X as skill, not job title

**Experience:** "X+ years", "X-Y years"
- "5+ years" → filters.min_experience = 5
- "3-7 years" → filters.min_experience = 3, filters.max_experience = 7

**Location:** City/country mentioned
- "in Bangalore" → filters.location = "Bangalore"

**Education:** Institute names or degrees
- "IIT graduates" → filters.institute = "IIT"
- "MBA candidates" → filters.degree = "MBA"

**Projects/Companies:** Keywords in work history
- "worked at Google" → filters.company = "Google"
- "built chatbot" → filters.project_keyword = "chatbot"

**MULTI-CRITERIA CRITICAL:** Extract ALL filters even if query has multiple types!
- "Python developers from IIT with 5+ years" → extract ALL three filters
- DO NOT skip any criteria

════════════════════════════════
STEP 3: CLASSIFY QUERY TYPE
════════════════════════════════
Choose ONE primary type:
- skill_based: "Python developers", "candidates with AWS"
- education_based: "IIT graduates", "MBA candidates"
- experience_based: "5+ years experience", "worked at Google"
- contact_based: "phone is X", "email is Y"
- project_based: "built X project"
- general: Broad questions without specific filters

════════════════════════════════
STEP 4: CHOOSE SEARCH STRATEGY
════════════════════════════════
**sql_only** - Exact matches only, return ALL SQL results:
- Name/phone/email lookup: "Find John Smith", "phone 8374106843"
- Education lookup: "IIT graduates", "MBA from NIT"
- Use when: No semantic ranking needed

**sql_first** - Filter with SQL, return ALL matches:
- Multi-criteria: "Python developers with 5+ years in Bangalore"
- Use when: Clear filters, want all matches (not just top 10)

**vector_first** - Semantic search ONLY (no SQL filtering):
- Subjective keywords: "rare", "unique", "interesting", "innovative", "creative", "impressive", "exceptional"
- Examples: "Most rare projects", "Unique backgrounds", "Similar to Elon Musk"
- Returns: Top 10 semantically relevant
- Use when: CANNOT determine with SQL logic

**hybrid** - SQL filter + vector ranking:
- "Python developers with interesting projects"
- SQL filters exact criteria (Python), vector ranks by relevance
- Returns: Top 10 after filtering

════════════════════════════════
STEP 5: SQL COMPLEXITY DECISION
════════════════════════════════
**use_llm_sql = False** (use hardcoded filters):
- Simple lookups: "Find John", "Python developers"
- Basic filters: "5+ years experience", "candidates in Bangalore"
- 2-3 simple criteria: "Python developers in Mumbai with 3+ years"

**use_llm_sql = True** (generate custom SQL):
- AGGREGATIONS: "how many", "count", "average", "total"
  • Set is_aggregation_query=True
  • Example: "How many Python developers?"
  
- RANKINGS: "best", "top", "most", "highest", "lowest", "maximum", "minimum"
  • Example: "Who has the most experience?" → ORDER BY DESC LIMIT 1
  • WARNING: Always use LLM SQL for rankings!
  
- COMPLEX LOGIC: 4+ OR clauses, nested conditions
  • Example: "(Python OR Java) AND (AWS OR Azure OR GCP)"

Set sql_complexity_reason to explain your decision.

════════════════════════════════
STEP 6: Q&A QUERY DETECTION
════════════════════════════════
**Set is_qa_query = True** if query asks to ANALYZE/EXPLAIN/SUGGEST based on previous context WITHOUT needing new database search:

Examples that DON'T need search:
- "Suggest 10 technical questions based on his resume"
- "Explain why he is suitable for this role"
- "What are his strengths and weaknesses?"
- "Summarize his experience"
- "Compare these two candidates"
- "Why should we hire him?"

These queries use data from PREVIOUS conversation context - NO database search needed!
**Set is_qa_query = True and skip all other analysis.**""",
            ),
        ]
    )

    chain = analysis_prompt | llm.with_structured_output(QueryAnalysis)

    try:
        analysis = chain.invoke(
            {
                "query": state["query"],  # ✅ Original query unchanged
                "chat_context": chat_context,  # ✅ Context passed separately
            }
        )

        state["query_analysis"] = analysis.model_dump()
        state["search_strategy"] = analysis.search_strategy
        state["sql_filters"] = analysis.filters.model_dump()
        state["use_llm_sql"] = analysis.use_llm_sql  # Set flag from analysis

        print(f"\n🧠 QUERY ANALYSIS:")
        print(f"   Type: {analysis.query_type}")
        print(f"   Strategy: {analysis.search_strategy}")
        print(f"   Reasoning: {analysis.reasoning}")
        print(f"   Confidence: {analysis.confidence:.2f}")
        
        # Check if this is a Q&A query that doesn't need search
        if analysis.is_qa_query:
            print(f"   💬 Q&A QUERY: No search needed - will use previous context")
            # conversation_context already set earlier with most_recent_candidates
        
        
        if analysis.use_llm_sql:
            print(f"   🤖 LLM SQL: YES - {analysis.sql_complexity_reason}")
        else:
            print(f"   ⚡ SQL Mode: Hardcoded filters")
        
        # Explain what will happen based on strategy
        if analysis.search_strategy in ["sql_only", "sql_first"]:
            print(f"   📊 Result source: SQL (all matching candidates, no vector limit)")
        elif analysis.search_strategy == "vector_first":
            print(f"   🔍 Result source: Vector search (top 10 semantic matches)")
        elif analysis.search_strategy == "hybrid":
            print(f"   🔀 Result source: SQL + Vector (top 10 from SQL matches)")
        if chat_context:
            print(
                f"   📜 Used conversation context ({len(state['chat_history'])} messages)"
            )

    except Exception as e:
        print(f"⚠️  Analysis failed: {e}. Defaulting to hybrid search.")
        state["query_analysis"] = {"error": str(e)}
        state["search_strategy"] = "hybrid"
        state["sql_filters"] = {}

    return state


def sql_filter_node(state: AgentState) -> AgentState:
    """
    Node 2: Execute SQL filtering based on extracted entities

    Only runs if strategy requires SQL (sql_first, sql_only, hybrid)
    Routes to LLM SQL if query analysis indicates complexity
    """

    if state["search_strategy"] == "vector_first":
        print("\n📊 SKIPPING SQL (vector-first strategy)")
        state["candidate_ids"] = []
        return state

    # Check if analysis recommends LLM SQL
    analysis = state.get("query_analysis", {})
    if analysis.get("use_llm_sql", False):
        print("\n📊 ROUTING TO LLM SQL GENERATION...")
        print(f"   Reason: {analysis.get('sql_complexity_reason', 'Complex query detected')}")
        state["use_llm_sql"] = True
        return state

    print("\n📊 EXECUTING HARDCODED SQL FILTERS...")

    filters = state["sql_filters"]
    analysis = state["query_analysis"]
    
    # Check if user wants to filter from previous results ("out of these", "from them", "out of all", etc.)
    query_lower = state["query"].lower()
    context_filter_phrases = [
        "out of these", "from these", "from those", "among these", 
        "among them", "out of them", "from the above", "from previous",
        "out of the", "from the ", "among the ", "within these",
        "in these", "in the above",
        # CRITICAL: "out of all X" phrases that reference previous results
        "out of all the", "out of all those", "from all the", "from all these",
        "among all the", "among all those", "within all the"
    ]
    is_context_filter = any(phrase in query_lower for phrase in context_filter_phrases)
    
    # Get previous candidate IDs from conversation context
    previous_candidate_ids = state.get("conversation_context", {}).get("candidate_ids", [])
    
    if is_context_filter and previous_candidate_ids:
        print(f"   🔗 CONTEXT FILTERING: Restricting search to previous {len(previous_candidate_ids)} candidates")
        # Override candidate_ids to enforce context filtering
        filters["candidate_ids"] = previous_candidate_ids
        state["sql_filters"]["candidate_ids"] = previous_candidate_ids
        
        # CRITICAL: When filtering from context, CLEAR any redundant filters that were already applied
        # For example: "out of these JavaScript developers" - JavaScript was already filtered in previous query
        # We only want to check for NEW criteria (like "machine learning") within the context
        # 
        # Strategy: Keep candidate_ids filter + only NEW criteria mentioned in current query

    # Build SQL query dynamically
    import os

    db_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "resumes.db"
    )
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    where_clauses = []
    params = []

    # ✅ PRIORITY: Check if explicit names are mentioned in the query
    # If yes, ignore candidate_ids filter (user wants fresh search for those names)
    entities = analysis.get("entities", {})
    has_explicit_names = bool(entities.get("names"))
    
    # ✅ Candidate IDs filter (for follow-up queries) - ONLY if no explicit names
    if filters.get("candidate_ids") and not has_explicit_names:
        candidate_id_list = filters["candidate_ids"]
        placeholders = ",".join("?" * len(candidate_id_list))
        where_clauses.append(f"resume_id IN ({placeholders})")
        params.extend(candidate_id_list)
        print(
            f"   🎯 Follow-up query: Filtering to {len(candidate_id_list)} previously discussed candidates"
        )

    # Extract names from entities (process names even if candidate_ids was set)
    if has_explicit_names:
        names = entities["names"]
        if len(names) > 1:
            # Multiple names: match ANY of them with OR
            name_or_conditions = []
            for name in names:
                name_parts = name.strip().split()
                if len(name_parts) >= 2:
                    # Multi-part name: match all parts with AND
                    name_and_parts = []
                    for part in name_parts:
                        name_and_parts.append("candidate_name LIKE ?")
                        params.append(f"%{part}%")
                    name_or_conditions.append(f"({' AND '.join(name_and_parts)})")
                else:
                    # Single name part
                    name_or_conditions.append("candidate_name LIKE ?")
                    params.append(f"%{name}%")
            
            where_clauses.append(f"({' OR '.join(name_or_conditions)})")
            print(f"   🎯 Name filter: Matching ANY of {len(names)} names: {', '.join(names)}")
        else:
            # Single name
            name = names[0]
            name_parts = name.strip().split()
            if len(name_parts) >= 2:
                # Multi-part name: match all parts (prevents partial matches)
                name_conditions = []
                for part in name_parts:
                    name_conditions.append("candidate_name LIKE ?")
                    params.append(f"%{part}%")
                where_clauses.append(f"({' AND '.join(name_conditions)})")
                print(f"   🎯 Name filter: Matching all parts of '{name}'")
            else:
                # Single name: use simple LIKE
                where_clauses.append("candidate_name LIKE ?")
                params.append(f"%{name}%")

    # Experience filters
    if filters.get("min_experience"):
        where_clauses.append("total_experience_years >= ?")
        params.append(filters["min_experience"])

    if filters.get("max_experience"):
        where_clauses.append("total_experience_years <= ?")
        params.append(filters["max_experience"])

    # Location filter
    if filters.get("location"):
        where_clauses.append("location LIKE ?")
        params.append(f"%{filters['location']}%")

    # Skills filter with intelligent expansion for abbreviations and synonyms
    if filters.get("required_skills"):
        # Define skill name expansions (abbreviations, synonyms, related terms)
        skill_expansions = {
            # AI/ML Skills
            "gen ai": ["Gen AI", "Generative AI", "GenAI", "LLM", "GPT", "Large Language Model"],
            "generative ai": ["Gen AI", "Generative AI", "GenAI", "LLM", "GPT"],
            "ml": ["ML", "Machine Learning", "machine learning"],
            "machine learning": ["ML", "Machine Learning", "machine learning"],
            "ai": ["AI", "Artificial Intelligence", "artificial intelligence"],
            "nlp": ["NLP", "Natural Language Processing", "natural language processing"],
            "cv": ["CV", "Computer Vision", "computer vision", "image processing"],
            "deep learning": ["Deep Learning", "DL", "Neural Networks", "deep learning"],
            
            # Programming Languages
            "js": ["JS", "JavaScript", "Javascript", "javascript"],
            "javascript": ["JS", "JavaScript", "Javascript", "javascript"],
            "ts": ["TS", "TypeScript", "Typescript", "typescript"],
            "typescript": ["TS", "TypeScript", "Typescript"],
            "py": ["Python", "python", "py"],
            "python": ["Python", "python"],
            
            # Frameworks/Libraries
            "react": ["React", "ReactJS", "React.js", "react"],
            "reactjs": ["React", "ReactJS", "React.js"],
            "angular": ["Angular", "AngularJS", "Angular.js"],
            "vue": ["Vue", "VueJS", "Vue.js"],
            "node": ["Node", "NodeJS", "Node.js", "node.js"],
            "nodejs": ["Node", "NodeJS", "Node.js"],
            
            # Cloud/DevOps
            "aws": ["AWS", "Amazon Web Services", "amazon web services"],
            "gcp": ["GCP", "Google Cloud Platform", "Google Cloud", "google cloud"],
            "azure": ["Azure", "Microsoft Azure", "azure"],
            "k8s": ["K8s", "Kubernetes", "kubernetes"],
            "kubernetes": ["K8s", "Kubernetes", "kubernetes"],
            "docker": ["Docker", "docker", "containerization"],
            
            # Data/Databases
            "sql": ["SQL", "sql", "MySQL", "PostgreSQL", "database"],
            "nosql": ["NoSQL", "MongoDB", "Cassandra", "DynamoDB"],
            "mongodb": ["MongoDB", "Mongo", "mongo"],
            
            # Other
            "rest": ["REST", "RESTful", "REST API", "restful api"],
            "api": ["API", "REST API", "Web API", "api"],
        }
        
        # CRITICAL: When we have multiple skills, we need to decide AND vs OR logic
        # - If context filtering is active: Use AND (all skills must match within the filtered set)
        # - If no context filtering: Use OR (any skill can match)
        
        skill_groups = []  # Each group is a list of OR conditions for one skill
        
        for skill in filters["required_skills"]:
            skill_lower = skill.lower().strip()
            skill_conditions = []
            
            # Check if skill has known expansions
            if skill_lower in skill_expansions:
                # Add OR conditions for all variations of this ONE skill
                variations = skill_expansions[skill_lower]
                for variation in variations:
                    skill_conditions.append("skills LIKE ?")
                    params.append(f"%{variation}%")
                print(f"   💡 Skill '{skill}' expanded to: {', '.join(variations)}")
            else:
                # No expansion - use as-is
                skill_conditions.append("skills LIKE ?")
                params.append(f"%{skill}%")
            
            # Group the variations for this skill (OR within the group)
            if skill_conditions:
                skill_groups.append(f"({' OR '.join(skill_conditions)})")
        
        # Now combine skill groups based on context
        if skill_groups:
            if is_context_filter and len(skill_groups) > 1:
                # Context filtering with multiple skills: Use AND
                # Example: "out of these JavaScript developers, who has machine learning"
                # → Must have BOTH JavaScript AND Machine Learning
                where_clauses.append(f"({' AND '.join(skill_groups)})")
                print(f"   🔗 Context mode: Requiring ALL {len(skill_groups)} skills (AND logic)")
            else:
                # Normal search or single skill: Use OR
                # Example: "Find JavaScript or Python developers"
                where_clauses.append(f"({' OR '.join(skill_groups)})")
                if len(skill_groups) > 1:
                    print(f"   🔍 Normal mode: Matching ANY of {len(skill_groups)} skills (OR logic)")

    # Job title filter (searches in work_experience JSON and current_role)
    if filters.get("job_title"):
        job_title = filters["job_title"]
        # Search in both work_experience JSON and current_role column
        where_clauses.append("(work_experience LIKE ? OR current_role LIKE ?)")
        params.append(f"%{job_title}%")
        params.append(f"%{job_title}%")

    # Company filter (searches in work_experience JSON)
    if filters.get("company"):
        where_clauses.append("work_experience LIKE ?")
        params.append(f"%{filters['company']}%")

    # Current role filter (exact match in current_role column)
    if filters.get("current_role"):
        where_clauses.append("current_role LIKE ?")
        params.append(f"%{filters['current_role']}%")

    # Phone filter (flexible matching - removes formatting characters)
    if filters.get("phone"):
        phone = filters["phone"]
        # Remove common phone formatting characters for flexible matching
        phone_clean = phone.replace("-", "").replace(" ", "").replace("(", "").replace(")", "").replace("+", "")
        where_clauses.append("REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(phone, '-', ''), ' ', ''), '(', ''), ')', ''), '+', '') LIKE ?")
        params.append(f"%{phone_clean}%")
        print(f"   📞 Phone filter: {phone}")

    # Email filter
    if filters.get("email"):
        where_clauses.append("email LIKE ?")
        params.append(f"%{filters['email']}%")
        print(f"   📧 Email filter: {filters['email']}")

    # Institute filter (searches in education JSON)
    # Smart expansion for common institutes (IIT, NIT, BITS, etc.)
    if filters.get("institute"):
        institute_name = filters["institute"]
        
        # Define common institute abbreviation expansions
        institute_expansions = {
            "IIT": ["IIT", "Indian Institute of Technology"],
            "NIT": ["NIT", "National Institute of Technology"],
            "BITS": ["BITS", "Birla Institute of Technology and Science"],
            "IIIT": ["IIIT", "Indian Institute of Information Technology"],
            "IIM": ["IIM", "Indian Institute of Management"],
            "ISI": ["ISI", "Indian Statistical Institute"],
            "AIIMS": ["AIIMS", "All India Institute of Medical Sciences"],
        }
        
        # Check if the institute matches any known abbreviation (case-insensitive)
        institute_upper = institute_name.upper().strip()
        expanded_names = None
        
        # Exact match or starts with the abbreviation
        for abbrev, expansions in institute_expansions.items():
            if institute_upper == abbrev or institute_upper.startswith(abbrev + " "):
                expanded_names = expansions
                break
        
        if expanded_names:
            # Create OR clause for all variations
            institute_conditions = []
            for variation in expanded_names:
                institute_conditions.append("education LIKE ?")
                params.append(f"%{variation}%")
            where_clauses.append(f"({' OR '.join(institute_conditions)})")
            print(f"   🎓 Institute filter: {institute_name} → Searching for: {', '.join(expanded_names)}")
        else:
            # No expansion needed - use as-is
            where_clauses.append("education LIKE ?")
            params.append(f"%{institute_name}%")
            print(f"   🎓 Institute filter: {institute_name}")

    # Degree filter (searches in education JSON)
    if filters.get("degree"):
        where_clauses.append("education LIKE ?")
        params.append(f"%{filters['degree']}%")
        print(f"   📜 Degree filter: {filters['degree']}")

    # Project keyword filter (searches in projects JSON)
    if filters.get("project_keyword"):
        where_clauses.append("projects LIKE ?")
        params.append(f"%{filters['project_keyword']}%")
        print(f"   💼 Project filter: {filters['project_keyword']}")

    # Build final query
    sql = "SELECT resume_id FROM parsed_resumes"
    if where_clauses:
        sql += " WHERE " + " AND ".join(where_clauses)

    print(f"   SQL: {sql}")
    print(f"   Params: {params}")

    cursor.execute(sql, params)
    results = cursor.fetchall()
    conn.close()

    candidate_ids = [row[0] for row in results]
    state["candidate_ids"] = candidate_ids

    print(f"   ✅ Found {len(candidate_ids)} candidates via SQL")

    # If no results and this was a sql_only query, mark for LLM SQL retry
    if not candidate_ids and state["search_strategy"] == "sql_only":
        state["use_llm_sql"] = True

    return state


def llm_sql_generation_node(state: AgentState) -> AgentState:
    """
    Node 2.5: Generate SQL query using LLM for complex queries

    Invoked when query analysis detects complexity (aggregations, comparisons, etc.)
    OR on retry when predefined SQL filters don't work.
    LLM gets complete schema and generates appropriate SQL.
    """

    # Only run if use_llm_sql flag is set
    if not state.get("use_llm_sql"):
        return state

    print("\n🤖 GENERATING SQL WITH LLM...")
    
    # Use comprehensive database schema
    schema_info = DATABASE_SCHEMA

    # Check if this is an aggregation query
    analysis = state.get("query_analysis", {})
    is_aggregation = analysis.get("is_aggregation_query", False)
    
    if is_aggregation:
        select_instruction = "2. For aggregation queries (how many, count, average), use COUNT(*), AVG(), SUM(), MAX(), MIN() - NOT resume_id"
    else:
        select_instruction = "2. Always SELECT resume_id for candidate search queries"
    
    sql_generation_prompt = f"""
You are a SQL expert. Generate a SQLite query to answer this user question.

DATABASE SCHEMA:
{schema_info}

USER QUESTION: {state["query"]}

RULES:
1. ONLY return the SQL query, nothing else
{select_instruction}
3. Use LIKE for text matching with % wildcards
4. For experience, use total_experience_years (it's a number)
5. For skills, search in the skills column (JSON array as text)
6. For phone numbers, use: REPLACE(REPLACE(REPLACE(phone, '-', ''), ' ', ''), '+', '') LIKE '%cleanednumber%'
7. For email, use: email LIKE '%emailpattern%'
8. For education/institute, search in education column: education LIKE '%institutename%'
9. For degree, search in education column: education LIKE '%degreename%'
10. For projects, search in projects column: projects LIKE '%projectname%'
11. For companies, search in work_experience column: work_experience LIKE '%companyname%'
12. For achievements/certifications, search in additional_information column

EXAMPLES:

CANDIDATE SEARCH QUERIES (return resume_id):
- "whose contact is 8374106843" → SELECT resume_id FROM parsed_resumes WHERE REPLACE(REPLACE(REPLACE(phone, '-', ''), ' ', ''), '+', '') LIKE '%8374106843%'
- "find email john@example.com" → SELECT resume_id FROM parsed_resumes WHERE email LIKE '%john@example.com%'
- "candidates with Python" → SELECT resume_id FROM parsed_resumes WHERE skills LIKE '%Python%'
- "who studied at IIT Delhi" → SELECT resume_id FROM parsed_resumes WHERE education LIKE '%IIT Delhi%'
- "MBA graduates" → SELECT resume_id FROM parsed_resumes WHERE education LIKE '%MBA%'
- "worked at Google" → SELECT resume_id FROM parsed_resumes WHERE work_experience LIKE '%Google%'
- "Python developers with 5+ years from IIT" → SELECT resume_id FROM parsed_resumes WHERE skills LIKE '%Python%' AND total_experience_years >= 5 AND education LIKE '%IIT%'

AGGREGATION QUERIES (return COUNT/AVG/SUM/MAX/MIN):
- "How many Python developers?" → SELECT COUNT(*) FROM parsed_resumes WHERE skills LIKE '%Python%'
- "How many candidates from IIT?" → SELECT COUNT(*) FROM parsed_resumes WHERE education LIKE '%IIT%'
- "What's the average experience?" → SELECT AVG(total_experience_years) FROM parsed_resumes
- "Average experience of Python developers?" → SELECT AVG(total_experience_years) FROM parsed_resumes WHERE skills LIKE '%Python%'
- "Total candidates with AWS" → SELECT COUNT(*) FROM parsed_resumes WHERE skills LIKE '%AWS%'

RANKING QUERIES (return resume_id with ORDER BY LIMIT):
- "Who has the most experience?" → SELECT resume_id FROM parsed_resumes ORDER BY total_experience_years DESC LIMIT 1
- "Top 5 candidates by experience" → SELECT resume_id FROM parsed_resumes ORDER BY total_experience_years DESC LIMIT 5

SQL QUERY:
"""

    try:
        response = llm.invoke(sql_generation_prompt)
        generated_sql = response.content.strip()

        # Clean up the SQL (remove markdown code blocks if present)
        if "```" in generated_sql:
            generated_sql = generated_sql.split("```")[1]
            if generated_sql.startswith("sql"):
                generated_sql = generated_sql[3:]
            generated_sql = generated_sql.strip()

        print(f"   Generated SQL: {generated_sql}")

        # Execute the generated SQL
        import os

        db_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "resumes.db"
        )
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        cursor.execute(generated_sql)
        results = cursor.fetchall()
        conn.close()

        # Check if this is an aggregation query
        analysis = state.get("query_analysis", {})
        is_aggregation = analysis.get("is_aggregation_query", False)
        
        if is_aggregation:
            # For aggregations, store the result value, not resume_ids
            aggregation_result = results[0][0] if results else 0
            state["aggregation_result"] = aggregation_result
            state["candidate_ids"] = []  # No candidate IDs for aggregations
            state["llm_generated_sql"] = generated_sql
            print(f"   ✅ LLM SQL aggregation result: {aggregation_result}")
        else:
            # For candidate searches, extract resume_ids
            candidate_ids = [row[0] for row in results]
            state["candidate_ids"] = candidate_ids
            state["llm_generated_sql"] = generated_sql
            print(f"   ✅ LLM SQL found {len(candidate_ids)} candidates")

    except Exception as e:
        print(f"   ❌ LLM SQL failed: {str(e)}")
        state["candidate_ids"] = []

    return state


def vector_search_node(state: AgentState) -> AgentState:
    """
    Node 3: Execute vector search with optional metadata filtering

    CRITICAL LOGIC:
    - sql_only/sql_first: Skip vector search, use SQL results directly (SQL is authoritative)
    - vector_first: Use vector search with optional SQL filters (semantic ranking needed)
    - hybrid: Use vector search with SQL filters (combine exact + semantic)
    """
    
    # Skip vector search for aggregation queries (they just need the number, not candidate details)
    analysis = state.get("query_analysis", {})
    if analysis.get("is_aggregation_query", False):
        print("\n🔍 SKIPPING VECTOR SEARCH (aggregation query - no candidates needed)")
        state["search_results"] = {}
        return state

    # For sql_only or sql_first strategies with SQL results, skip vector search entirely
    # Vector search would only reduce the results (top_k limitation)
    if state["search_strategy"] in ["sql_only", "sql_first"] and state["candidate_ids"]:
        print(f"\n🔍 SKIPPING VECTOR SEARCH ({state['search_strategy']} strategy)")
        print(f"   ✅ Using ALL {len(state['candidate_ids'])} candidates from SQL directly")
        print(f"   💡 Vector search would reduce results due to top_k limit")

        # Create mock search results with just the resume_ids from SQL
        state["search_results"] = {
            "ids": [[f"{rid}__direct" for rid in state["candidate_ids"]]],
            "metadatas": [[{"resume_id": rid} for rid in state["candidate_ids"]]],
            "documents": [["" for _ in state["candidate_ids"]]],
            "distances": [[0.0 for _ in state["candidate_ids"]]],
        }
        return state

    print("\n🔍 EXECUTING VECTOR SEARCH...")
    print(f"   Strategy: {state['search_strategy']} - Using semantic ranking")

    # Use vector store directly (not HybridResumeSearch) to apply ChromaDB filters correctly
    from vectorstore.chroma_store import ResumeVectorStore

    vector_store = ResumeVectorStore()

    # Prepare metadata filter if we have candidate IDs from SQL (hybrid strategy)
    vector_filters = None
    if state["candidate_ids"]:
        vector_filters = {"resume_id": {"$in": state["candidate_ids"]}}
        print(f"   🎯 Filtering to {len(state['candidate_ids'])} candidates from SQL")
        print(f"   ⚠️  Note: Will return top 10 most relevant (not all {len(state['candidate_ids'])})")

    # Execute search directly on vector store with proper filter format
    results = vector_store.search(
        query=state["vector_query"], top_k=10, filters=vector_filters
    )

    state["search_results"] = results

    print(f"   ✅ Found {len(results.get('ids', [[]])[0])} vector matches")

    return state


def enrich_results_node(state: AgentState) -> AgentState:
    """
    Node 4: Fetch full resume data from SQLite and deduplicate
    
    Handles same resume appearing multiple times (different chunks) from vector search results
    """
    
    # Skip enrichment for aggregation queries
    analysis = state.get("query_analysis", {})
    if analysis.get("is_aggregation_query", False):
        print("\n💎 SKIPPING ENRICHMENT (aggregation query - returning aggregated value)")
        state["final_results"] = []
        state["should_retry"] = False
        return state

    print("\n💎 ENRICHING RESULTS...")

    if not state["search_results"] or not state["search_results"].get("metadatas"):
        state["final_results"] = []
        state["should_retry"] = True
        return state

    # Deduplicate by resume_id (keep ALL chunks for each resume)
    resume_chunks = {}  # {resume_id: [list of chunks]}
    metadatas = state["search_results"]["metadatas"][0]
    documents = state["search_results"]["documents"][0]
    distances = state["search_results"]["distances"][0]

    for meta, doc, dist in zip(metadatas, documents, distances):
        resume_id = meta.get("resume_id")
        
        if resume_id not in resume_chunks:
            resume_chunks[resume_id] = []
        
        # Store ALL chunks for this resume (not just highest scoring)
        resume_chunks[resume_id].append({
            "chunk_type": meta.get("chunk_type"),
            "chunk_text": doc,
            "distance": dist,
            "metadata": meta
        })

    unique_ids = list(resume_chunks.keys())
    print(
        f"   Deduplicated: {len(metadatas)} chunks → {len(unique_ids)} unique resumes"
    )

    # Fetch full data from SQLite
    import os

    db_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "resumes.db"
    )
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    placeholders = ",".join("?" * len(unique_ids))
    query = f"""
        SELECT 
            pr.*,
            d.raw_text
        FROM parsed_resumes pr
        LEFT JOIN documents d ON pr.document_id = d.document_id
        WHERE pr.resume_id IN ({placeholders})
    """

    cursor.execute(query, unique_ids)
    rows = cursor.fetchall()
    conn.close()

    final_results = []
    for row in rows:
        resume_dict = dict(row)
        resume_id = resume_dict['resume_id']
        
        # ✅ NEW: Add matched chunks to resume data
        resume_dict['matched_chunks'] = resume_chunks.get(resume_id, [])
        
        final_results.append(resume_dict)

    state["final_results"] = final_results

    print(f"   ✅ Enriched {len(final_results)} resumes with full data + matched chunks")

    # Decide if we should retry
    state["should_retry"] = len(final_results) == 0

    return state


def fetch_context_candidates_node(state: AgentState) -> AgentState:
    """
    Node: Fetch candidate data from conversation context for Q&A queries
    
    This node only runs for Q&A queries that skip search.
    It fetches the full resume data for candidates from previous conversation.
    """
    
    print("\n💬 FETCHING CANDIDATES FROM CONVERSATION CONTEXT...")
    
    # Get candidate IDs from conversation context (set by analyze_query_node)
    context = state.get("conversation_context", {})
    candidate_ids = context.get("candidate_ids", [])
    candidate_names = context.get("candidate_names", [])
    
    if not candidate_ids:
        print("   ⚠️  No candidates in conversation context")
        state["final_results"] = []
        return state
    
    print(f"   📋 Found {len(candidate_ids)} candidates from previous conversation")
    for i, (cid, name) in enumerate(zip(candidate_ids, candidate_names), 1):
        print(f"      {i}. {name} ({cid})")
    
    # Fetch full data from SQLite
    import os
    
    db_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "resumes.db"
    )
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    placeholders = ",".join("?" * len(candidate_ids))
    query = f"""
        SELECT 
            pr.*,
            d.raw_text
        FROM parsed_resumes pr
        LEFT JOIN documents d ON pr.document_id = d.document_id
        WHERE pr.resume_id IN ({placeholders})
    """

    cursor.execute(query, candidate_ids)
    rows = cursor.fetchall()
    conn.close()

    final_results = []
    for row in rows:
        resume_dict = dict(row)
        # No matched_chunks for Q&A queries (we're not searching)
        resume_dict['matched_chunks'] = []
        final_results.append(resume_dict)

    state["final_results"] = final_results
    print(f"   ✅ Fetched full data for {len(final_results)} candidates")
    
    return state


def generate_answer_node(state: AgentState) -> AgentState:
    """
    Node 5: Generate natural language answer using LLM

    Uses existing answer generation function
    """

    print("\n🤖 GENERATING ANSWER...")
    
    # Handle aggregation queries - return the number directly
    analysis = state.get("query_analysis", {})
    if analysis.get("is_aggregation_query", False):
        aggregation_result = state.get("aggregation_result", 0)
        query_lower = state["query"].lower()
        
        # Format answer based on query type
        if "how many" in query_lower or "count" in query_lower:
            state["answer"] = f"There are **{aggregation_result} candidates** matching your criteria."
        elif "average" in query_lower or "avg" in query_lower:
            state["answer"] = f"The average is **{aggregation_result:.2f}**."
        elif "total" in query_lower or "sum" in query_lower:
            state["answer"] = f"The total is **{aggregation_result}**."
        else:
            state["answer"] = f"Result: **{aggregation_result}**"
        
        print(f"   ✅ Aggregation answer: {aggregation_result}")
        return state

    if not state["final_results"]:
        state["answer"] = (
            "I couldn't find any candidates matching your criteria. Try:\n- Broadening your search terms\n- Removing some filters\n- Checking for typos in names or skills"
        )
        return state

    # ✅ SMART FORMAT SELECTION: Detailed profiles vs compact list
    total_candidates = len(state["final_results"])
    query_lower = state["query"].lower()
    
    # Check if user wants LIST ALL candidates (not detailed profiles)
    wants_list_all = any(phrase in query_lower for phrase in [
        "list all", "show all", "all candidates", "find all", 
        "list candidates", "all of them"
    ])
    
    # Check if user wants DETAILED profiles
    wants_detailed = any(phrase in query_lower for phrase in [
        "detailed profile", "tell me about", "show me details", "full details",
        "in detail", "detailed information", "tell me more about",
        "who is", "what is their", "what are their", "show their",
        "education", "experience", "projects", "skills of", "background",
        "contact", "email", "phone", "work history", "achievements", "certifications"
    ])
    
    # Check if user wants only TOP N candidates
    wants_top_n = any(phrase in query_lower for phrase in [
        "top 5", "best 5", "top five", "best five", "show me 5",
        "top 3", "best 3", "top three"
    ])
    
    # DECISION LOGIC:
    # 1. If explicitly wants "list all" → compact list format, ALL candidates
    if wants_list_all:
        print(f"   📋 'List all' detected: Showing ALL {total_candidates} candidates in compact format")
        results_to_use = state["final_results"]
        format_as_list = True
    
        # 2. If wants detailed info (education/experience/etc) → detailed profiles
    elif wants_detailed:
        # ✅ FIXED: If user wants ALL previous ("their", "these"), show ALL, don't limit to 5
        wants_all_from_previous = any(phrase in query_lower for phrase in [
            "their", "these", "those", "all of them", "all their", "all these"
        ])
        print(f"   📄 Detailed query: Showing all {total_candidates} candidates")
        results_to_use = state["final_results"]
        format_as_list = False
    
    # 3. If wants top N → detailed profiles, limited
    elif wants_top_n:
        results_to_use = state["final_results"][:5]
        format_as_list = False
        print(f"   📄 Top N query: Showing top 5 of {total_candidates} candidates")
    
    # 4. DEFAULT: If 10+ candidates → compact list, otherwise detailed profiles
    elif total_candidates >= 10:
        print(f"   📋 Many results ({total_candidates}): Using compact format")
        results_to_use = state["final_results"]
        format_as_list = True
    
    else:
        # 1-9 candidates: Show detailed profiles
        print(f"   📄 Few results ({total_candidates}): Using detailed format")
        results_to_use = state["final_results"]
        format_as_list = False
    
    query_lower = state["query"].lower()
    
    # Check if user explicitly wants ALL previous candidates
    # Include "their" which is commonly used ("show me their education")
    wants_all_previous = any(phrase in query_lower for phrase in [
        "all of these", "all of them", "all these", "all candidates",
        "for all", "of all", "each of these", "every one of them",
        "all their", "all previous", "for each", "their education",
        "their experience", "their skills", "their projects", "their work",
        "their contact", "show me their", "what are their"
    ])
    
    is_specific_query = any(keyword in query_lower for keyword in [
        "this candidate", "the candidate", "that candidate"
    ])
    
    # ✅ INTENT-AWARE FILTERING: Only filter to single candidate if this is truly a follow-up query
    # NOT a search query asking "which candidates have X"
    # AND NOT when user wants ALL previous candidates
    
    # Indicators of SEARCH queries (should show ALL results):
    search_indicators = [
        "which candidate",
        "find candidate",
        "show me candidate",
        "list candidate",
        "who has",
        "candidates with",
        "find me",
        "search for"
    ]
    
    is_search_query = any(indicator in query_lower for indicator in search_indicators)
    
    # Skip single-candidate filtering if user wants ALL previous
    if wants_all_previous:
        print(f"   📋 'ALL' detected: Showing information for ALL {len(results_to_use)} candidates")
    # If asking about specific candidate AND we have candidate_ids filter (follow-up from chat history)
    elif is_specific_query and state["sql_filters"].get("candidate_ids") and not is_search_query:
        candidate_id = state["sql_filters"]["candidate_ids"][0]
        # Filter to only this candidate
        results_to_use = [r for r in results_to_use if r["resume_id"] == candidate_id]
        print(f"   🎯 Specific query detected: Showing ONLY candidate {candidate_id}")
    
    # OR if name was specified AND it's a follow-up query (not a search)
    # Example: "show me John's education" → filter to John only
    # But NOT: "which candidate named John has Python" → show John in results but don't filter others
    elif state["query_analysis"].get("entities", {}).get("names") and not is_search_query:
        specified_names = state["query_analysis"]["entities"]["names"]
        
        # ✅ FIXED: If multiple names mentioned, show ALL of them (don't filter to one)
        if len(specified_names) > 1:
            # Multiple names explicitly mentioned - show all matching candidates
            print(f"   📋 Multiple names query: Showing ALL {len(results_to_use)} candidates")
        else:
            # Single name - check if we should filter to just that candidate
            specified_name = specified_names[0].lower()
            name_matches = [r for r in results_to_use if specified_name in r.get("candidate_name", "").lower()]
            if len(name_matches) == 1:
                results_to_use = name_matches
                print(f"   🎯 Single candidate query: Showing ONLY {name_matches[0]['candidate_name']}")
            elif len(name_matches) > 1:
                # Multiple candidates with similar names - show all
                print(f"   📋 Found {len(name_matches)} candidates matching '{specified_name}' - showing all")
    
    answer = generate_answer(
        query=state["query"], search_results=results_to_use, format_as_list=format_as_list
    )

    state["answer"] = answer

    print(f"   ✅ Answer generated ({len(answer)} chars)")

    return state


def should_retry_node(state: AgentState) -> Literal["retry", "end"]:
    """
    Router: Decide whether to retry with different strategy

    On retry, enable LLM SQL generation for complex queries
    """

    if state["should_retry"] and state.get("retry_count", 0) < 1:
        print("\n🔄 NO RESULTS - RETRYING WITH LLM SQL GENERATION...")
        state["retry_count"] = state.get("retry_count", 0) + 1
        state["use_llm_sql"] = True  # Enable LLM SQL on retry

        # Switch strategy to vector_first if SQL failed
        if state["search_strategy"] in ["sql_first", "sql_only"]:
            state["search_strategy"] = "vector_first"
        else:
            state["search_strategy"] = "hybrid"

        return "retry"

    return "end"


# ============= Build Graph =============


def create_intelligent_agent() -> StateGraph:
    """
    Build the LangGraph workflow for intelligent resume search

    Flow:
    1. Analyze query → 2. SQL filter → 2.5. LLM SQL (if needed) → 3. Vector search →
    4. Enrich results → 5. Generate answer → Retry if needed
    """

    workflow = StateGraph(AgentState)

    # Add nodes
    workflow.add_node("analyze_query", analyze_query_node)
    workflow.add_node("sql_filter", sql_filter_node)
    workflow.add_node("llm_sql_generation", llm_sql_generation_node)  # NEW
    workflow.add_node("vector_search", vector_search_node)
    workflow.add_node("enrich_results", enrich_results_node)
    workflow.add_node("fetch_context_candidates", fetch_context_candidates_node)  # NEW: For Q&A queries
    workflow.add_node("generate_answer", generate_answer_node)

    # Define edges
    workflow.set_entry_point("analyze_query")
    
    # Add conditional routing after analysis
    # - If Q&A query → fetch candidates from context, then generate answer
    # - Otherwise → proceed to SQL filtering
    def route_after_analysis(state: AgentState) -> Literal["sql_filter", "fetch_context_candidates"]:
        """Route based on whether this is a Q&A query or search query"""
        analysis = state.get("query_analysis", {})
        if analysis.get("is_qa_query", False):
            return "fetch_context_candidates"  # Fetch context candidates, then answer
        return "sql_filter"
    
    workflow.add_conditional_edges(
        "analyze_query",
        route_after_analysis,
        {"sql_filter": "sql_filter", "fetch_context_candidates": "fetch_context_candidates"}
    )
    
    # Q&A queries: fetch context → generate answer
    workflow.add_edge("fetch_context_candidates", "generate_answer")
    
    workflow.add_edge("sql_filter", "llm_sql_generation")  # Try LLM SQL if needed
    workflow.add_edge("llm_sql_generation", "vector_search")
    workflow.add_edge("vector_search", "enrich_results")
    workflow.add_edge("enrich_results", "generate_answer")

    # Conditional retry logic
    workflow.add_conditional_edges(
        "generate_answer",
        should_retry_node,
        {"retry": "sql_filter", "end": END},  # Go back and try different strategy
    )

    return workflow.compile()


# ============= Easy-to-Use Interface =============


class ResumeIntelligenceAgent:
    """
    Main agent interface - handles everything automatically

    Usage:
        agent = ResumeIntelligenceAgent()
        answer = agent.query("Find Python developers with 5+ years")
    """

    def __init__(self):
        self.graph = create_intelligent_agent()

    def query(
        self, user_query: str, session_id: str = None, verbose: bool = True
    ) -> dict:
        """
        Process a query and return natural language answer

        The agent will automatically:
        - Load conversation history (if session_id provided)
        - Save user message to database
        - Analyze the query to understand intent
        - Choose the best search strategy (SQL, vector, or hybrid)
        - Execute the search with appropriate filters
        - Deduplicate results
        - Generate a helpful answer
        - Save agent response to database
        - Retry with different strategy if needed

        Args:
            user_query: The user's question
            session_id: Optional session ID to continue a conversation
            verbose: Whether to print debug information

        Returns:
            Dict with keys: 'answer', 'session_id', 'candidate_ids'
        """
        # Import chat manager
        from chat.chat_manager import (
            create_chat_session,
            save_user_message,
            save_agent_message,
            load_chat_history,
        )

        # Create or use existing session
        if not session_id:
            session_id = create_chat_session(
                title=user_query
            )  # Use first 50 chars as title
            chat_history = []
        else:
            chat_history = load_chat_history(session_id, limit=10)

        # Save user message
        user_msg_id = save_user_message(session_id, user_query)

        if verbose:
            print("=" * 70)
            print(f"📝 USER QUERY: {user_query}")
            if chat_history:
                print(
                    f"💬 CONTINUING SESSION: {session_id} ({len(chat_history)} previous messages)"
                )
            else:
                print(f"🆕 NEW SESSION: {session_id}")
            print("=" * 70)

        # Initialize state with chat history
        initial_state = {
            "query": user_query,
            "query_analysis": {},
            "search_strategy": "hybrid",
            "sql_filters": {},
            "vector_query": user_query,
            "candidate_ids": [],
            "search_results": [],
            "final_results": [],
            "answer": "",
            "should_retry": False,
            "retry_count": 0,
            "use_llm_sql": False,
            "llm_generated_sql": "",
            "aggregation_result": 0,
            "chat_history": chat_history,  # ✅ Load from database
            "conversation_context": {},  # ✅ Will be populated from chat history
        }

        # Run the graph
        final_state = self.graph.invoke(initial_state)

        # Extract results
        answer = final_state["answer"]
        final_results = final_state.get("final_results", [])
        candidate_ids = [result.get("resume_id") for result in final_results]
        candidate_names = [result.get("candidate_name") for result in final_results]  # ✅ NEW
        query_analysis = final_state.get("query_analysis", {})
        search_strategy = final_state.get("search_strategy", "unknown")

        # Save agent message with names AND IDs
        agent_msg_id = save_agent_message(
            session_id=session_id,
            content=answer,
            candidate_ids=candidate_ids,
            candidate_names=candidate_names,  # ✅ NEW
            search_type=search_strategy,
            query_analysis=query_analysis,
        )

        if verbose:
            print("\n" + "=" * 70)
            print("✅ FINAL ANSWER:")
            print("=" * 70)
            print(answer)
            print("=" * 70)
            print(f"💾 Saved to session: {session_id}")
            if candidate_ids:
                print(f"👥 Returned {len(candidate_ids)} candidates")
            print("=" * 70)

        return {
            "answer": answer,
            "session_id": session_id,
            "candidate_ids": candidate_ids,
        }


# ============= Testing =============

if __name__ == "__main__":
    agent = ResumeIntelligenceAgent()

    print("\n🤖 CONVERSATIONAL AGENT TEST\n")

    # First query - creates new session
    print("━" * 70)
    print("TEST 1: New conversation")
    print("━" * 70)
    result1 = agent.query("Find Python developers with more than 5 years experience")
    session_id = result1["session_id"]

    print(f"\n📊 Result: Found {len(result1['candidate_ids'])} candidates")
    print(f"🆔 Session ID: {session_id}")

    # Follow-up query - uses context
    print("\n" + "━" * 70)
    print("TEST 2: Follow-up question (should understand 'their')")
    print("━" * 70)
    result2 = agent.query("Show me their projects", session_id=session_id)

    print(f"\n📊 Result: {len(result2['candidate_ids'])} candidates")

    # Another follow-up
    print("\n" + "━" * 70)
    print("TEST 3: Another follow-up (should use same candidates)")
    print("━" * 70)
    result3 = agent.query("What are their skills?", session_id=session_id)

    print(f"\n📊 Result: {len(result3['candidate_ids'])} candidates")

    print("\n✅ CONVERSATIONAL TEST COMPLETE!")